apiVersion: v1
kind: Service
metadata:
  name: poc-app-service
spec:
  type: NodePort
  selector:
    app: poc-app
  ports:
    - protocol: TCP
      port: 8080        # Service port
      targetPort: 8080  # Container port
      nodePort: 30081   # Port exposed on host machine (accessible via localhost:30080)
